name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps

      - name: Build library
        run: |
          npx ng build ngx-easy-table
          npx node-sass projects/ngx-easy-table/assets/style.scss dist/ngx-easy-table/style.css || npx sass projects/ngx-easy-table/assets/style.scss dist/ngx-easy-table/style.css
          cp projects/ngx-easy-table/assets/style.scss dist/ngx-easy-table/style.scss

      - name: Create tarball
        run: |
          cd dist/ngx-easy-table
          npm pack
          mv *.tgz ../../ngx-easy-table-${{ github.ref_name }}.tgz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ngx-easy-table-${{ github.ref_name }}.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
