name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps --ignore-scripts
          npm rebuild --ignore-scripts
          npm install -g sass

      - name: Verify installation
        run: |
          node --version
          npm --version
          npx ng version || echo "Angular CLI check failed"
          sass --version

      - name: Build library
        run: |
          npx --yes @angular/cli@9.0.3 build ngx-easy-table
          sass projects/ngx-easy-table/assets/style.scss dist/ngx-easy-table/style.css
          cp projects/ngx-easy-table/assets/style.scss dist/ngx-easy-table/style.scss

      - name: Create tarball
        run: |
          cd dist/ngx-easy-table
          npm pack
          mv *.tgz ../../ngx-easy-table-${{ github.ref_name }}.tgz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ngx-easy-table-${{ github.ref_name }}.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
